In [13]:
import numpy as np
a = np.arange(2,14).reshape(3,4)
print(a)
print(np.argmin(a))#find the min number's index
print(np.argmax(a))#find the max number's index
print('---------------------------')
print(np.mean(a))#calculate the arange's average
print(a.mean())#equal the up code
print(np.average(a))
print('--------median---------')
print(np.median(a))
print('-----------')
print(np.cumsum(a))
print(np.diff(a))
print(np.nonzero(a))
print(np.sort(a))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
---------------------------
7.5
7.5
7.5
--------median---------
7.5
-----------
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [14]:
print(np.clip(a,5,9))


[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]


In [17]:
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

[6. 7. 8. 9.]
[ 3.5  7.5 11.5]
