In [2]:
import numpy as np
a = np.array([1,1,1])
b = np.array([2,2,2])
print(a)
print(b)

[1 1 1]
[2 2 2]


In [5]:
print(np.vstack((a,b)))#vertical stack

[[1 1 1]
 [2 2 2]]


In [6]:
#see the shape
c = np.vstack((a,b))
print(a.shape,c.shape)

(3,) (2, 3)


In [9]:
d = np.hstack((a,b))#horizontal stack
print(d)
print(d.shape,a.shape)

[1 1 1 2 2 2]
(6,) (3,)


In [11]:
#from horizontal to vertical
print(a[:,np.newaxis])
print(a[:,np.newaxis].shape)

[[1]
 [1]
 [1]]
(3, 1)


In [16]:
a = np.array([1,1,1])[:,np.newaxis]
b = np.array([2,2,2])[:,np.newaxis]
print(a)
print(b)
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[[1]
 [1]
 [1]]
[[2]
 [2]
 [2]]
[[1 2]
 [1 2]
 [1 2]]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]


In [20]:
f = np.concatenate((a,b,a,b),axis=0)
print(f)
g = np.concatenate((a,b,a,b),axis=1)
print(g)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]]
[[1 2 1 2]
 [1 2 1 2]
 [1 2 1 2]]
