In [11]:
import numpy as np
#create an array named a
a = np.array([1,22,3],dtype=np.float)
print(a)
print(a.dtype)

[ 1. 22.  3.]
float64


In [13]:
# an all zeros matrix
b = np.zeros((3,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
#a matrix all of number is one
c = np.ones((3,3),dtype=np.int16)
print(c)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [25]:
#a empty matrix approximately zero,but not zero
d = np.empty((3,4))
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
#the numbers from ten to eighty, and between number part of two
e = np.arange(10,80,2)
print(e)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78]


In [28]:
#there are twelve numbers,and the matrix shape is three rows and four columns
f = np.arange(12).reshape((3,4))
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
#the numbers from one to ten,there are five average part number
g = np.linspace(1,10,5)
print(g)

[ 1.    3.25  5.5   7.75 10.  ]


In [38]:
#modify the linspace's shape
h = np.linspace(1,10,6).reshape((2,3))
print(h)

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]
