In [8]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)#an array from zero to three
print(a,b)
print('--------addition--------------')
c = a + b
print(c)
print('-----------substruction--------------')
d = a - b
print(d)
print('-------------multiplication-------------')
e = a * b
print(e)
print('-------------square----------')
f = a**2
print(f)

[10 20 30 40] [0 1 2 3]
--------addition--------------
[10 21 32 43]
-----------substruction--------------
[10 19 28 37]
-------------multiplication-------------
[  0  20  60 120]
-------------square----------
[ 100  400  900 1600]


In [12]:
#trigonometric function
g = np.sin(a)#each number in a calculation sin number
print(g)
h = np.cos(a)
print(h)
i = np.tan(a)
print(i)

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 0.64836083  2.23716094 -6.4053312  -1.11721493]


In [14]:
#if the number of b is be smaller three print True, else print False
print(b)
print(b<3)
print(b==3)

[0 1 2 3]
[ True  True  True False]
[False False False  True]


In [19]:
#matrix's operations
x = np.array([[1,1],[0,1]])
y = np.arange(4).reshape((2,2))
print(x)
print(y)
print('----------------------------------------')
j = x * y
k = np.dot(x,y)
print(j)#same position number calculation
print(k)#the matrix calculation method
k2 = x.dot(y)#compare k the same result,but different method
print(k2)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
----------------------------------------
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [24]:
# a random matrix from zero to one
z = np.random.random((2,4))
print(z)
print(np.sum(z))
print(np.min(z))
print(np.max(z))
print('----------------------')
print(np.min(z,axis=0))#find the min number in every column
print(np.max(z,axis=1))#find the max number in every row

[[0.86867396 0.22940151 0.28434443 0.16688232]
 [0.63800731 0.05432881 0.40046714 0.0025449 ]]
2.64465038516882
0.0025449039021242514
0.868673957276928
----------------------
[0.63800731 0.05432881 0.28434443 0.0025449 ]
[0.86867396 0.63800731]
