In [8]:
import numpy as np
a = np.arange(3,15).reshape(3,4)
print(a)
print(a[2])
print(a[1][2])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
9


In [12]:
print(a[2,1])

12


In [13]:
print(a[2,:])

[11 12 13 14]


In [17]:
print(a[:,1])

[ 4  8 12]


In [18]:
print(a[1,0:2])

[7 8]


In [19]:
print(a[0,1:3])

[4 5]


In [9]:
b = np.arange(3,15)
print(b)
print(b[2])

[ 3  4  5  6  7  8  9 10 11 12 13 14]
5


In [20]:
for row in a:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [24]:
print(a)
print(a.T)
for column in a.T:
    print(column)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[[ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]
 [ 6 10 14]]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [27]:
print(a.flatten())
for item in a.flat:
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14
