In [4]:
import numpy as np
a = np.arange(4)
print(a)

[0 1 2 3]


In [5]:
b = a
c = a
d = b
print(b,c,d)

[0 1 2 3] [0 1 2 3] [0 1 2 3]


In [6]:
a[0] = 8
print(a,b,c,d)

[8 1 2 3] [8 1 2 3] [8 1 2 3] [8 1 2 3]


In [7]:
b is a

True

In [8]:
d[1:3] = [22,32]
print(d)

[ 8 22 32  3]


In [10]:

print(a,b,c,d)

[ 8 22 32  3] [ 8 22 32  3] [ 8 22 32  3] [ 8 22 32  3]


In [11]:
d is a

True

In [14]:
d = a.copy()#deep copy
print(a,d)
a[2] = 67
print(a,d)

[ 8 22 32  3] [ 8 22 32  3]
[ 8 22 67  3] [ 8 22 32  3]


In [15]:
d is a

False